title: Luke Bemish
email: lukebemish@lukebemish.dev
description: >-
  I'm a graduate student interested in systems neuroscience! This is my blog
baseurl: ""
url: "https://lukebemish.dev"
domain: "lukebemish.dev"
github_username: lukebemish
repository: lukebemish/lukebemish.github.io
show_downloads: false
author: Luke Bemish
paginate: 5

collections:
  category:
    output: true
    permalink: /categories/:slugified_categories:output_ext

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-octicons
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-redirect-from
  - jekyll-webp
markdown: kramdown
permalink: /:year/:month/:day/:title:output_ext
kramdown:
  input: GFM
  hard_wrap: false
  gfm_quirks: paragraph_end
  syntax_highlighter_opts:
    default_lang: plaintext
  template: ""
  math_engine: mathjax
  syntax_highlighter: rouge
exclude:
  - CNAME
sass:
  style: compressed
highlighter: rouge
gist:
  noscript: false
authors:
  "Luke Bemish":
    gravatar: lukebemish@lukebemish.dev
    fediverse: "@lukebemish@mastodon.social"
social:
  - icon: envelope
    icon_category: solid
    url: mailto:lukebemish@lukebemish.dev
    me: true
  - icon:	github
    url:	https://github.com/lukebemish
    me: true
  - icon: mastodon
    url: https://mastodon.social/@lukebemish
    me: true
  - icon: linkedin
    url: https://www.linkedin.com/in/luke-bemish/
    me: true
    share_url: https://www.linkedin.com/sharing/share-offsite/?
    share_link: url=
  - icon: rss
    icon_category: solid
    me: false
    url: /feed.xml
webp:
  enabled: true
  img_dir: ["/assets/img/"]
  nested: true